import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body>
      <div className=' relative bg-[#F8FAFB]'>
          <div className='hidden h-full md:flex md:w-64 md:flex-col md:fixed md:inset-y-0 '>
            <Sidebar />
          </div>
          <main className='md:pl-64 '>
              {children}
          </main>
      </div>
      </body>
    </html>
  );
}
